### ISSUE TITLE
Service panics when deployed to Kubernetes

### ISSUE THREAD

**Issue by kahara** [kahara/go-gnssaggr#6]
```
{"level":"debug","time":"2022-02-20T21:21:31.682991407Z","message":"Connected to green.lan:2947"}
{"level":"debug","time":"2022-02-20T21:21:40.053111564Z","message":"Creating metric gdop"}
{"level":"debug","time":"2022-02-20T21:21:40.053206973Z","message":"Creating metric hdop"}
{"level":"debug","time":"2022-02-20T21:21:40.053315117Z","message":"Creating metric pdop"}
{"level":"debug","time":"2022-02-20T21:21:40.053415866Z","message":"Creating metric tdop"}
{"level":"debug","time":"2022-02-20T21:21:40.053473629Z","message":"Creating metric vdop"}
{"level":"debug","time":"2022-02-20T21:21:40.053551832Z","message":"Creating metric xdop"}
{"level":"debug","time":"2022-02-20T21:21:40.053625005Z","message":"Creating metric ydop"}
{"level":"debug","time":"2022-02-20T21:21:40.053668132Z","message":"Creating metric satellites"}
panic: JSON decoder out of sync - data changing underfoot?

goroutine 35 [running]:
encoding/json.(*decodeState).object(0xc00028ae10, {0x805220, 0xc00015e0f0, 0xb})
	/usr/local/go/src/encoding/json/decode.go:676 +0x1b0b
encoding/json.(*decodeState).value(0xc00028ae10, {0x805220, 0xc00015e0f0, 0x0})
	/usr/local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).array(0xc00028ae10, {0x7cf560, 0xc0002440e0, 0xf8a})
	/usr/local/go/src/encoding/json/decode.go:561 +0x626
encoding/json.(*decodeState).value(0xc00028ae10, {0x7cf560, 0xc0002440e0, 0xc00029007c})
	/usr/local/go/src/encoding/json/decode.go:363 +0x7e
encoding/json.(*decodeState).object(0xc00028ae10, {0x7c7640, 0xc000244080, 0xc000225d30})
	/usr/local/go/src/encoding/json/decode.go:774 +0xca5
encoding/json.(*decodeState).value(0xc00028ae10, {0x7c7640, 0xc000244080, 0x90})
	/usr/local/go/src/encoding/json/decode.go:373 +0x45
encoding/json.(*decodeState).unmarshal(0xc00028ae10, {0x7c7640, 0xc000244080})
	/usr/local/go/src/encoding/json/decode.go:180 +0x1de
encoding/json.Unmarshal({0xc000290000, 0x552cb4, 0x862db4}, {0x7c7640, 0xc000244080})
	/usr/local/go/src/encoding/json/decode.go:107 +0x125
github.com/kahara/go-gnssaggr/src/reader.parser(0x0, 0xc0000b0d80)
	/workdir/src/reader/parser.go:22 +0xec
created by github.com/kahara/go-gnssaggr/src/reader.Read
	/workdir/src/reader/reader.go:36 +0x145
```

**Comment by kahara** [comment]
`go run -race ./src` says:

```
{"level":"debug","time":"2022-02-20T23:55:02.665846056+02:00","message":"Connected to green.lan:2947"}
==================
WARNING: DATA RACE
Write at 0x00c000339220 by goroutine 9:
  runtime.racewriterange()
      <autogenerated>:1 +0x29
  internal/poll.ignoringEINTRIO()
      /usr/local/go/src/internal/poll/fd_unix.go:582 +0x454
  internal/poll.(*FD).Read()
      /usr/local/go/src/internal/poll/fd_unix.go:163 +0x26
  net.(*netFD).Read()
      /usr/local/go/src/net/fd_posix.go:56 +0x50
  net.(*conn).Read()
      /usr/local/go/src/net/net.go:183 +0xb0
  net.(*TCPConn).Read()
      <autogenerated>:1 +0x64
  bufio.(*Scanner).Scan()
      /usr/local/go/src/bufio/scan.go:215 +0x13d5
  github.com/kahara/go-gnssaggr/src/reader.Read()
      /home/kahara/code/go-gnssaggr/src/reader/reader.go:66 +0x83d
  main.main·dwrap·1()
      /home/kahara/code/go-gnssaggr/src/main.go:41 +0x64

Previous read at 0x00c000339226 by goroutine 13:
  encoding/json.checkValid()
      /usr/local/go/src/encoding/json/scanner.go:32 +0x11b
  encoding/json.Unmarshal()
      /usr/local/go/src/encoding/json/decode.go:101 +0xc4
  github.com/kahara/go-gnssaggr/src/reader.parser()
      /home/kahara/code/go-gnssaggr/src/reader/parser.go:20 +0x16b
  github.com/kahara/go-gnssaggr/src/reader.Read·dwrap·1()
      /home/kahara/code/go-gnssaggr/src/reader/reader.go:36 +0x47

Goroutine 9 (running) created at:
  main.main()
      /home/kahara/code/go-gnssaggr/src/main.go:41 +0x344

Goroutine 13 (running) created at:
  github.com/kahara/go-gnssaggr/src/reader.Read()
      /home/kahara/code/go-gnssaggr/src/reader/reader.go:36 +0x1d8
  main.main·dwrap·1()
      /home/kahara/code/go-gnssaggr/src/main.go:41 +0x64
==================
```
